#!/usr/bin/env sh
set -eu

root="$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)"
version="$(tr -d '[:space:]' < "$root/VERSION")"
generated_dir="$root/docs/.vitepress/generated"

mkdir -p "$generated_dir" "$root/docs/reference"

cat > "$generated_dir/version.ts" <<EOF
// Generated by scripts/docs-metadata.sh. Do not edit by hand.
export const proxctlVersion = '${version}'
export const releaseUrl = 'https://github.com/kehr/Proxctl/releases/tag/${version}'
export const latestInstallerUrl = 'https://github.com/kehr/Proxctl/releases/latest/download/install.sh'
export const releaseDownloadUrl = 'https://github.com/kehr/Proxctl/releases/download/${version}'
export const artifactBaseName = 'proxctl-${version}'
export const releaseAssets = [
  'proxctl-${version}-linux-amd64.tar.gz',
  'proxctl-${version}-linux-arm64.tar.gz',
  'proxctl-${version}-darwin-amd64.tar.gz',
  'proxctl-${version}-darwin-arm64.tar.gz',
  'proxctl-${version}-windows-amd64.zip',
  'checksums.txt',
  'install.sh'
]
EOF

{
  cat <<EOF
# Release Notes

This page is generated at documentation build time from the repository \`VERSION\` file.

- Current version: \`${version}\`
- Release: [GitHub ${version}](https://github.com/kehr/Proxctl/releases/tag/${version})

EOF
  "$root/scripts/release-notes.sh" "$version"
} > "$root/docs/reference/release-notes.md"
